service: crud-serverless-users

provider:
  name: aws
  runtime: nodejs16.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action: "dynamodb:*"
          Resource: arn:aws:dynamodb:us-east-1:620097380428:table/usersTable

plugins:
  - serverless-better-credentials
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline

package:
  individually: true
  patterns:
    - "!*/**"
    - pkg/*.js

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
    # Uncomment only if you already have a DynamoDB running locally
    # noStart: true

functions:
  get-users:
    handler: lambdas/get-users/handler.getUsers
    package:
      patterns:
        - "lambdas/get-users/handler.js"
    events:
      - http:
          path: users/{id}
          method: GET
          request:
            parameters:
              paths:
                id: true

  create-user:
    handler: lambdas/create-user/handler.createUser
    package:
      patterns:
        - "lambdas/create-user/handler.js"
    events:
      - http:
          path: users
          method: POST

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
